# Generated by Django 4.1 on 2022-08-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='is_loaned',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='loan_date',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='return_date',
        ),
    ]
