# Generated by Django 4.1 on 2022-08-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0002_remove_publication_is_loaned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
