# Generated by Django 4.1 on 2022-08-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0003_loan_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['pub_date']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
    ]
